apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.backend.app }}
    project: {{ .Values.project }}
  name: {{ .Values.backend.app }}
spec:
  replicas: {{ .Values.replicacount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.app }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.backend.app }}
    spec:
      containers:
      - image: "{{ .Values.backend.repository }}:{{ .Values.backend.tag}}"
        imagePullPolicy: {{ .Values.backend.pullPolicy }}
        name: {{ .Values.backend.app }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
