apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.backend.app }}
    project: {{ .Values.project }}
  name: {{ .Values.backend.servicename }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.backend.app }}
  sessionAffinity: None
  type: ClusterIP
