apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: {{ .Values.backend.app }}
      project: {{ .Values.project }}
    name: {{ .Values.backend.app }}
  spec:
    port:
      targetPort: 8080
    tls:
      termination: edge
    to:
      kind: Service
      name: {{ .Values.frontend.servicename }}
      weight: 100
    wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
